### PR TITLE
using yml to store info of 收支記錄

### PR DESCRIPTION
**Pull request by wildskyf**
- about #25 (收支記錄)

### CODE REVIEW

**Comment by wildskyf** [comment]
[ issue opened ]

> By the way, the balance of party15 and 14 look strange.
> In balance of 14, it is 19997.
> However, it is 15829 in 15.

**Comment by wildskyf** [comment]
@kidwm yml 的值要怎麼取用…

**Comment by kidwm** [comment]
http://jekyllrb.com/docs/datafiles/

**Comment by kidwm** [comment]
@wi1d5ky 你可以把 facebook 串連社群的 data 也拉出來

**Pull request merged**
