### PR TITLE
Remove redundancy js code

### PR DESCRIPTION
**Pull request by wildskyf**
1. replace json with array (groups)
2. use id to select dom (it's because I can't get the name in getJson, and it's also the reason why I use array instead of json)
3. use for_in in order to remove redundancy js code

There is something wrong in facebook api, so that I can't get certain informations, such as cover_photo, description of groups. It cause that I should append what I need one by one. Besides, I have to give something to avoid `undefined` appear.

### CODE REVIEW

**Comment by kidwm** [comment]
可以用一下 `class="title"` 之類的吧。

groups 的 id array 其實可以從 HTML 裡面抓出來，這樣其實是資料重複出現了。

**Comment by wildskyf** [comment]
class="title"? 不太懂@@

好，`資料重複`我改一下

**Comment by kidwm** [comment]
就是不必 `div > div` 這樣選啦

**Comment by wildskyf** [comment]
改好了～

**Pull request merged**
